### ISSUE TITLE
pip install brokenaxes failed

### ISSUE THREAD

**Issue by andrewfowlie** [bendichter/brokenaxes#9]
I see the error:

```
  Downloading brokenaxes-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m8qZrr/brokenaxes/setup.py", line 10, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-m8qZrr/brokenaxes/README.md'
```

**Comment by bendichter** [comment]
shoot, sorry... not sure what's going on here but I'll figure it out

**Comment by bendichter** [comment]
looks like it's a python2-specific issue. If you can, try in python3 while I figure this out

**Comment by bendichter** [comment]
or use a previous version

**Comment by andrewfowlie** [comment]
No big deal, I just cloned it and built it from source with no problems. I would have been using python2.7
